- name: Update packages
  ansible.builtin.apt:
    update_cache: true
    upgrade: true

- name: Install essential packages
  ansible.builtin.package:
    name: "{{ packages }}"
    state: present

- name: Download docker-compose package
  command: wget https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-linux-armv6 -O /usr/local/bin/docker-compose
  become: yes

- name: Add execute permision to docker-compose bin
  command: chmod +x /usr/local/bin/docker-compose
  become: yes
